version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:11.17-bullseye
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=clustercontrol